"""empty message

Revision ID: 57682f76f1db
Revises: 
Create Date: 2023-05-19 08:57:16.092250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57682f76f1db'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('city', sa.String(length=256), nullable=True),
    sa.Column('part_of_city', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('type_of_real_estate',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('category', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('real_estate',
    sa.Column('external_id', sa.String(length=256), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('offer', sa.String(length=256), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('square_meter', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('area', sa.Integer(), nullable=True),
    sa.Column('storey', sa.String(length=256), nullable=True),
    sa.Column('num_of_floors', sa.Integer(), nullable=True),
    sa.Column('registration', sa.Boolean(), nullable=True),
    sa.Column('heating_type', sa.String(length=256), nullable=True),
    sa.Column('num_of_rooms', sa.Integer(), nullable=True),
    sa.Column('num_of_toilets', sa.Integer(), nullable=True),
    sa.Column('parking', sa.Boolean(), nullable=True),
    sa.Column('elevator', sa.Boolean(), nullable=True),
    sa.Column('other', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['type_of_real_estate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('real_estate')
    op.drop_table('type_of_real_estate')
    op.drop_table('location')
    # ### end Alembic commands ###
