"""empty message

Revision ID: 90c665bf87dc
Revises: 
Create Date: 2023-05-12 18:39:55.417185

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '90c665bf87dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.alter_column('city',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.String(length=256),
               existing_nullable=True)
        batch_op.alter_column('part_of_city',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.String(length=256),
               existing_nullable=True)

    with op.batch_alter_table('real_estate', schema=None) as batch_op:
        batch_op.alter_column('storey',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=256),
               existing_nullable=True)
        batch_op.alter_column('registration',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.String(length=256),
               existing_nullable=True)
        batch_op.alter_column('heating_type',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=256),
               existing_nullable=True)
        batch_op.alter_column('parking',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=256),
               existing_nullable=True)
        batch_op.alter_column('elevator',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=256),
               existing_nullable=True)
        batch_op.alter_column('other',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=256),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('real_estate', schema=None) as batch_op:
        batch_op.alter_column('other',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('elevator',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.alter_column('parking',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.alter_column('heating_type',
               existing_type=sa.String(length=256),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('registration',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
        batch_op.alter_column('storey',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)

    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.alter_column('part_of_city',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=30),
               existing_nullable=True)
        batch_op.alter_column('city',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=30),
               existing_nullable=True)

    # ### end Alembic commands ###
