"""empty message

Revision ID: e58283a9eadd
Revises: 90c665bf87dc
Create Date: 2023-05-12 18:44:36.205251

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e58283a9eadd'
down_revision = '90c665bf87dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('real_estate', schema=None) as batch_op:
        batch_op.alter_column('offer',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=256),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('real_estate', schema=None) as batch_op:
        batch_op.alter_column('offer',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###
